name: CI

on:
  push:
    branches:
      - main

jobs:
  dotnet-setup:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Verify .NET
        run: |
          dotnet --info
          dotnet --version

      - name: Hello World
        run: echo "Hello World from self-hosted runner"